spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
  datasource:
    url: jdbc:h2:mem:bookstore
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
server:
  port: 8087

logging:
  level:
    org.hibernate.SQL: DEBUG
#  UPDATE BOOK set author = 'Krzystof'  where id = 1;