spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
  datasource:
    url: jdbc:mysql://localhost:3309/bookstore
    username: root
    password:
#    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
server:
  port: 8087

logging:
  level:
    org.hibernate.SQL: DEBUG
#  UPDATE BOOK set author = 'Krzystof'  where id = 1;